- name: check hostname
  win_command: hostname
  register: cmdOut
  
- name: ping output
  debug:
    msg: "{{ cmdOut }}"

- name: show snt code value
  debug: 
    var: sntCode

- name: show mgmtIP value
  debug: 
    var: mgmtIp

- name: show hostname value
  debug: 
    var: hostName
