---
- name: Running Post OS Provisioning steps  
  hosts: localhost
  tasks:
    - name: "check hostname"
      win_command: hostname
      delegate_to: "{{ hostName }}"
      register: cmdOut
  
    - name: print output
      debug:
        msg: "{{ cmdOut }}"

  roles: 
    - role: addDNSrecord
