---
- name: Running Post OS Provisioning steps  
  hosts: "{{ hostName }}"

- name: "check hostname"
  win_command: hostname
  register: cmdOut
  
- name: print output
  debug:
    msg: "{{ cmdOut }}"
  
  roles: 
    - role: addDNSrecord
  delegate_to: localhost
