---
- name: Running Post OS Provisioning steps  
  hosts: localhost
  roles: 
    - role: addDNSrecord
    - role: InstallConfigureSNMP
      delegate_to: "{{ hostName }}"

  tasks:
    - name: print output
      debug:
        msg: "This is printing on localhost - {{ hostName }}"    
