---
- name: Running Post OS Provisioning steps  
  hosts: localhost
  roles: 
    - role: InstallConfigureSNMP
      delegate_to: "{{ hostName }}"

- name: print output
  debug:
    msg: "This is printing on localhost - {{ hosts }}"
