- name: Create SAS user account
  hosts: localhost
  tasks:
    - name: Get username signed in to AWX
      debug:
        msg: "{{ awx_user_name }}"

    - name: set host fqdn variable
      set_fact: 
        fqdn: "{{ hostName }}.{{sntCode}}.{{ domainName }}" 

    - name: print fqdn
      debug:
        msg: "{{ fqdn }}"
      tags:
        - always
   
    - name: create user on target host
      win_user: 
        name: "sas-{{ awx_user_name }}"
        password: "{{ sas_Usr_Pwd }}"
        update_password: always
        description: "Sungard User"
        password_expired: no 
        state: present
        groups: "Users,Administrators,Remote Desktop Users"
      delegate_to: "{{ fqdn }}" 
      register: userOut

    - name: print userOut result
      debug: 
        msg: "{{ userOut }}"
      tags:
        - always
        
    - name: setting {{ userOut.name }} 
      debug:
        msg: "{{ userOut.name }} has been set successfully on {{ fqdn }}"
      when: userOut.changed == true

    #- name:  the username exists already
    - debug:
        msg: "{{ userOut.name }} already exists on {{ fqdn }}"
      when: userOut.changed == false
        
