- name: delete SAS user account
  hosts: "{{ hostName }}.{{sntCode}}.omi.local"
  tasks:
    - name: delete user sas-"{{ sasUserName }}" on "{{ hostName }}.{{sntCode}}.omi.local"
      win_user:  
        name: "sas-{{ sasUserName }}"
        state: absent
      when: sasUserName | length != 0
      register: userOut


    - name: print userOut result
      debug: 
        msg: "{{ userOut }}"
      tags: 
        - never   


    - name: delete user sas-"{{ awx_user_name }}" on "{{ hostName }}.{{sntCode}}.omi.local"
      win_user: 
        name: "sas-{{ awx_user_name }}"
        state: absent
      when: sasUserName | length == 0
      register: userOut1

    - name: print userOut1 result
      debug: 
        msg: "{{ userOut1 }}"
      tags: 
        - never
