- name: delete SAS user account
  hosts: "{{ hostName }}.{{sntCode}}.{{ domainName }}"
  tasks:
    - name: delete user sas-"{{ sasUserName }}" on "{{ hostName }}.{{sntCode}}.{{ domainName }}"
      win_user:  
        name: "sas-{{ sasUserName }}"
        state: absent
      when: sasUserName | length != 0
      register: userOut

    - name: print userOut result
      debug: 
        msg: "{{ userOut }}"
      tags: 
        - always   

    - name: Print the username deleted
      debug:
        msg: "{{ userOut.name }} has been deleted successfully on {{ hostName }}.{{sntCode}}.{{ domainName }}"
      when: userOut.changed == true

    - name: delete user sas-"{{ awx_user_name }}" on "{{ hostName }}.{{sntCode}}.{{ domainName }}"
      win_user: 
        name: "sas-{{ awx_user_name }}"
        state: absent
      when: sasUserName | length == 0
      register: userOut1

    - name: print userOut1 result
      debug: 
        msg: "{{ userOut1 }}"
      tags: 
        - always

    - name: Print the username deleted
      debug:
        msg: "{{ userOut1.name }} has been deleted successfully on {{ hostName }}.{{sntCode}}.{{ domainName }}"
      when: userOut1.changed == true
