- name: delete SAS user account
  hosts: localhost

  tasks:
    - name: set host fqdn variable
      set_fact: 
        fqdn: "{{ hostName }}.{{sntCode}}.{{ domainName }}" 

    #- name: print fqdn
    - debug:
        msg: "Target host: {{ fqdn }}"

    - name: add host to SAS Account inventory
      uri:
       url: http://bt-c9-stream-tmp.oamp.sgns.net/api/v2/inventories/{{ inventoryID }}/hosts/
       user: "{{ Mirror_UN }}"
       password: "{{ Mirror_PW }}"
       method: POST
       body: '{ "name" : "{{ fqdn }}" }'
       force_basic_auth: yes
       status_code: 201, 200, 400
       body_format: json
       validate_certs: no
      register: addHost

    - name: print add host to inventory result
      debug: 
        msg: "{{ addHost }}"
      tags:
        - never 
        
    - name: delete other user
      win_user:  
        name: "sas-{{ sasUserName }}"
        state: absent
      delegate_to: "{{ fqdn }}"
      when: sasUserName | length != 0
      register: userOut

    - name: print userOut result
      debug: 
        msg: "{{ userOut }}"
      tags: 
        - never  

    #- name: Print the username deleted
    - debug:
        msg: "{{ userOut.name }} has been deleted successfully on {{ fqdn }}"
      when: userOut.changed == true

    - debug:
        msg: "{{ userOut.name }} does not exist on {{ fqdn }}"
      when: ('msg' in userOut) and ('not found' in userOut.msg)

    - name: delete OAMP user
      win_user: 
        name: "sas-{{ awx_user_name }}"
        state: absent
      delegate_to: "{{ fqdn }}"
      when: sasUserName | length == 0
      register: userOut1

    - name: print userOut1 result
      debug: 
        msg: "{{ userOut1 }}"
      tags: 
        - never

    #- name: Print the username deleted
    - debug:
        msg: "{{ userOut1.name }} has been deleted successfully on {{ fqdn }}"
      when: userOut1.changed == true

    - debug:
        msg: "{{ userOut1.name }} does not exist on {{ fqdn }}"
      when: ('msg' in userOut1) and ('not found' in userOut1.msg)
