- name: delete SAS user account
  hosts: localhost

  tasks:
    - name: set host fqdn variable
      set_fact: 
        fqdn: "{{ hostName }}.{{sntCode}}.{{ domainName }}" 

    #- name: print fqdn
    - debug:
        msg: "Target host: {{ fqdn }}"


    - name: delete other user
      win_user:  
        name: "sas-{{ sasUserName }}"
        state: absent
      delegate_to: "{{ fqdn }}"
      when: sasUserName | length != 0
      register: userOut

    - name: print userOut result
      debug: 
        msg: "{{ userOut }}"
      tags: 
        - never   

    #- name: Print the username deleted
    - debug:
        msg: "{{ userOut.name }} has been deleted successfully on {{ fqdn }}"
      when: userOut.changed == true

    - name: delete OAMP user
      win_user: 
        name: "sas-{{ awx_user_name }}"
        state: absent
      delegate_to: "{{ fqdn }}"
      when: sasUserName | length == 0
      register: userOut1

    - name: print userOut1 result
      debug: 
        msg: "{{ userOut1 }}"
      tags: 
        - never

    #- name: Print the username deleted
    - debug:
        msg: "{{ userOut1.name }} has been deleted successfully on {{ fqdn }}"
      when: userOut1.changed == true
