- name: Post OS Common Tasks
  hosts: localhost
  
  tasks:
    - name: Print Message
      debug:
        msg: "Running Post OS Common Tasks!!"
        
    - name: Check IpAddress is registered with zone in DNS
      uri:
        url: https://esb-stage.tools.sgns.net:443/dns/lookup?query=10.66.241.175
        method: GET
        body_format: json
        headers: 
            content-type: application/json
            Authorization: "{{ Esb_Stg }}"
      register: hostFQDN
      
    - name: Check host fqdn is registered with zone in DNS
      uri:
        url: https://esb-stage.tools.sgns.net:443/dns/lookup?query=RAtest-win2k22M.sahd.omi.local
        method: GET
        body_format: json
        headers: 
            content-type: application/json
            Authorization: "{{ Esb_Stg }}"
      register: ipAddrs
      
    - name: add record
      uri:
        url: https://esb-stage.tools.sgns.net:443/dns/zone/sahd/records?create_zones=true
        method: Post
        body_format: json
        headers: 
            content-type: application/json
            Authorization: "{{ Esb_Stg }}"
        body: 
            [
                ["${targethostname}","${targetip}"]
            ]
        register: response
      when: hostFQDN.json.result != "RAtest-win2k22M.sahd.omi.local" || ipAddrs.json.result != "10.66.241.175"
       
    - name: printing response
      debug:
        msg: "{{ response }}"
        
    - 
