- name: Post OS Common Tasks
  hosts: localhost
  
  tasks:
    - name: Print Message
      debug:
        msg: "Running Post OS Common Tasks!!"
        
    - name: Check IpAddress is registered NNMI
      uri:
        url: https://esb-stage.tools.sgns.net:443/omsServices/ipmanage/nnmi/10.66.241.175
        method: GET
        body_format: json
        headers: 
            content-type: application/json
            Authorization: "{{ Esb_Stg }}"
        status_code: 200
      register: ipSeed
      
    - name: pring result
      debug: 
        msg: "{{ ipSeed }}"
        
    - name: add entry in to NNMI
      uri:
        url: https://esb-stage.tools.sgns.net:443/omsServices/ipmanage/nnmi
        method: Post
        body_format: json
        headers:
            content-type: application/json
            Authorization: "{{ Esb_Stg }}"
        status_code: 200, 201
        body: |-
              {
                "ip_address": "10.66.241.175",
                "location":"PA.PHILADELPHIA.287"
              }
      when: ipSeed.json | length == 0
      
    - name: Check IpAddress is registered with ucmdb
      uri:
        url: https://esb-stage.tools.sgns.net:443/omsServices/ipmanage/probes/10.66.241.175
        method: GET
        body_format: json
        headers: 
            content-type: application/json
            Authorization: "{{ Esb_Stg }}"
        status_code: 200
      register: cmdbseed
    
    - name: pring result
      debug: 
        msg: "{{ cmdbseed }}"  
        
    - name: add entry in to ucmdb
      uri:
        url: https://esb-stage.tools.sgns.net:443/omsServices/ipmanage/probes
        method: Post
        body_format: json
        headers:
            content-type: application/json
            Authorization: "{{ Esb_Stg }}"
        status_code: 200, 201
        body: |-
              {
                "ip_address": "10.66.241.175",
                "location":"PA.PHILADELPHIA.287"
              }
      when: (cmdbseed.json | length == 0) or (cmdbseed.json.excluded != "True")
      
    - name: Add entry in to ucmdb
        uri:
          url: https://esb-stage.tools.sgns.net:443/omsServices/ipmanage/probes
        method: Post
        body_format: json
        headers:
            content-type: application/json
            Authorization: "{{ Esb_Stg }}"
        status_code: 200, 201
        body: |-
              {
                "ip_address": "10.66.241.175",
                "probe":"{{ cmdbseed.json.probeName }}"
              }
      when: (cmdbseed.json.excluded == "True")
      
     
