- name: Post OS Common Tasks
  hosts: localhost
 
  tasks:
    - name: Print Message
      debug:
        msg: "Running Post OS Common Tasks!!"
        
    - name: Get Auth Token from SEPM
      uri:
        url: https://esb.tools.sgns.net:443/services/sepm/authToken?customerRegion=US
        method: Post
        body_format: json
        headers: 
            content-type: application/json
            Authorization: "{{ Esb_Prd }}"
        status_code: 200, 201
        body: |-
              {
                "username" : "{{ SEPM_UN }}",
                "password" : "{{ SEPM_PW }}",
                "domain" : ""
              }
      register: AuthKey
      changed_when: "'token' in AuthKey.json"

    - debug: var=AuthKey.json

    - name: print AuthKey
      debug: 
        msg: "{{ AuthKey.json.token }}"

    - name: Get computer details for the hostname given
      uri:
        url: https://esb.tools.sgns.net:443/services/sepm/group?customerRegion=US&authToken={{ AuthKey.json.token }}&computerName=RAtest-win2k22M
        method: Get
        body_format: json
        headers:
            content-type: application/json
            Authorization: "{{ Esb_Prd }}"
        status_code: 200, 201
      when: AuthKey.json.token | length != 0
      register: hostDetails

    - debug: var=hostDetails.json

    - name: print computer Name
      debug: 
        msg: "{{ hostDetails.json[0].name }}"

    - name: print hardwarekey
      debug:
        msg: "{{ hostDetails.json.hardwareKey }}"
      
