- name: Post OS Common Tasks
  hosts: localhost
  
  tasks:
    - name: Print Message
      debug:
        msg: "Running Post OS Common Tasks!!"
        
    - name: Check IpAddress is registered with ucmdb
      uri:
        url: https://esb-stage.tools.sgns.net:443/omsServices/ipmanage/probes/10.66.241.175
        method: GET
        body_format: json
        headers: 
            content-type: application/json
            Authorization: "{{ Esb_Stg }}"
        status_code: 200
      register: cmdbseed
    
    - name: pring result
      debug: 
        msg: "{{ cmdbseed }}"  
        
    - name: add entry in to ucmdb
      debug:
        msg: "identified json excluded"
      when: cmdbseed.json[0].excluded == "False"
     
