- name: Create SAS user account
  hosts: localhost
  tasks:
    # - name: Get username signed in to AWX
    #   debug:
    #     msg: "{{ awx_user_name }}"

    # - name: set host fqdn variable
    #   set_fact: 
    #     fqdn: "{{ hostName }}.{{sntCode}}.{{ domainName }}" 

    # #- name: print fqdn
    # - debug:
    #     msg: "Target host: {{ fqdn }}"
    #   tags:
    #     - always
        
    
    - name: create {{ sntCode }} group
      uri:
        url: http://bt-c9-stream-tmp.oamp.sgns.net/api/v2/groups/
        user: "{{ Mirror_UN }}"
        password: "{{ Mirror_PW }}"
        method: POST
        body: '{ "name" : "{{ sntCode }}", "description": "SNT Code: {{ sntCode }}", "inventory": "{{ inventId }}"  }'
        force_basic_auth: yes
        status_code: 201, 200, 400
        body_format: json
        validate_certs: no
      register: createGroup

    - name: print create group response
      debug: 
        msg: "{{ createGroup }}"
      tags:
        - always

    # - name: add {{ fqdn }} host to {{ sntCode }} group
    #   uri:
    #     url: http://bt-c9-stream-tmp.oamp.sgns.net/api/v2/groups/{{ createGroup.json.id }}/hosts/
    #     user: "{{ Mirror_UN }}"
    #     password: "{{ Mirror_PW }}"
    #     method: POST
    #     body: '{ "name": "{{ fqdn }}" }'
    #     force_basic_auth: yes
    #     status_code: 201, 200, 400
    #     body_format: json
    #     validate_certs: no
    #   when: createGroup.json | length !=0
