- name: Tools Agent Installation
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World"
    - name: copy file from UNC path
      win_copy: 
        src: \\awxfs.tools.sgns.net\test\Agents\
        dest: 'C:\sungard_files\'
        remote_src: True
