- name: Post OS Common Tasks
  hosts: localhost
 
  tasks:
    - name: Print Message
      debug:
        msg: "Running Post OS Common Tasks!!"
        
    - name: Get Auth Token from SEPM
      uri:
        url: https://esb.tools.sgns.net:443/services/sepm/authToken?customerRegion=US
        method: Post
        body_format: json
        headers: 
            content-type: application/json
            Authorization: "{{ Esb_Prd }}"
        status_code: 200, 201
        body: |-
              {
                "username" : "{{ SEPM_UN }}",
                "password" : "{{ SEPM_PW }}",
                "domain" : ""
              }
         return_content: yes     
      register: AuthKey
      
    - name: Print Authkey
      debug:
        msg: "{{ Authkey }}"
