- name: Tools Agent Installation
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World"
        
    - name: Check for omi directory and create if not exist.
      ansible.windows.win_file:
        path: 'C:\sungard_files\OMI'
        state: directory
        
    - name: copy file from url and unarchive to OMI
      ansible.windows.win_get_url:
        url: https://awxfs.tools.sgns.net/test/Agents/HPEOpsBAgent_Windows_12.20.05_BASE.zip
        dest: 'C:\sungard_files\OMI\'
        url_username: mahendra.ds
        url_password: Sparrow.34 
