---
- hosts: localhost
  tasks: 
    - name: create inventory
      uri: 
        url: http://bt-c9-stream-tmp.oamp.sgns.net/api/v2/inventories/
        user: "{{ Mirror_UN }}"
        password: "{{ Mirror_PW }}"
        body_format: json
        headers: 
            content-type: application/json
        method: POST  
        body: |-
              {
                "name": "TestInventory",
                  "description": "Testing inventory api",
                  "organization": "",
                  "kind": "",
                  "host_filter": "",
                  "variables": "ansible_port: 31457\nansible_winrm_transport: credssp\nansible_connection: winrm\nansible_winrm_scheme: https",
                  "insights_credential": ""
              }

