- name: Post OS Common Tasks
  hosts: localhost
 
  tasks:
    - name: Print Message
      debug:
        msg: "Running Post OS Common Tasks!!"
        
    - name: Get Auth Token from SEPM
      uri:
        url: https://esb.tools.sgns.net:443/services/sepm/authToken?customerRegion=US
        method: Post
        body_format: json
        headers: 
            content-type: application/json
            Authorization: "{{ Esb_Prd }}"
        status_code: 200, 201
        body: |-
              {
                "username" : "{{ SEPM_UN }}",
                "password" : "{{ SEPM_PW }}",
                "domain" : ""
              }
      register: AuthKey
      changed_when: "'token' in AuthKey.json"

    - debug: var=AuthKey.json

    - name: print AuthKey
      debug: 
        msg: "{{ AuthKey.json.token }}"

    - name: Get group details for the snt code given
      uri:
        url: https://esb.tools.sgns.net:443/services/sepm/group?customerRegion=US&authToken={{ AuthKey.json.token }}&groupName=SAHD&operator=contains
        method: Get
        body_format: json
        headers:
            content-type: application/json
            Authorization: "{{ Esb_Prd }}"
        status_code: 200, 201
      when: AuthKey.json.token | length != 0
      register: groupId

    - debug: var=groupId.json

    - name: print groupId
      debug: 
        msg: "{{ groupId.json[0].id }}"

    - name: print customer name
      debug:
        msg: "{{ groupId.json[0].name }}"
      when: groupId.json[0].name is not search("SAHD")
