- name: Post OS Common Tasks
  hosts: localhost
  
  tasks:
    - name: Print Message
      debug:
        msg: "Running Post OS Common Tasks!!"
        
    - name: delete record from Bind DNS
      uri:
        url: https://esb-stage.tools.sgns.net:443/dns/zone/${zoneName}/records
        method: delete
        body_format: json
        headers: 
            content-type: application/json
            Authorization: "{{ Esb_Stg }}"
        body: 
            [
                ["RAtest-win2k22M","10.66.241.175"]
            ]
        register: response
     
    - name: Print Response
      debug:
        msg: "{{ response }}"
      
     
