- name: Tools Agent Installation
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World"
    - name: copy file from UNC path
      win_copy: 
        src: \\phl2gmnpru02.oamp.sgns.net\Software\Provisioning\HPE_Tools\UD_Agent\ud_agents_11.60.zip
        dest: 'C:\sungard_files\'
        remote_src: True
