- name: Tools Agent Installation
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World"
    - name: Copy install OMI powershell script on to target
      win_copy: 
        src: files/scripts/OMIScripts
        dest: 'C:\sungard_files\'
        remote_src: no
