- name: Tools Agent Installation
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World"
        
    - name: Check for omi directory and create if not exist.
      ansible.windows.win_file:
        path: C:\sungard_files\OMI
        state: directory
        
    - name: copy file from url
      ansible.windows.win_get_url:
        url: https://awxfs.tools.sgns.net/test/Agents/HPEOpsBAgent_Windows_12.20.05_BASE.zip
        dest: 'C:\sungard_files\OMI\'
        url_username: "{{ Mirror_UN }}"
        url_password: "{{ Mirror_PW }}"
        
    - name: Unarchive to OMI folder
      ansible.windows.win_powershell:
        script: |
          Expand-Archive -Path "C:\sungard_files\OMI\HPEOpsBAgent_Windows_12.20.05_BASE.zip" -DestinationPath "C:\sungard_files\OMI" -Force   
