- name: OMI Tool Agent Installation
  hosts: all
  become: true
  tasks:
    - name: Print Message
      debug:
        msg: "OMI Agent Installation!!"
        
    - name: Check for omi directory and create if not exist.
      file:
        path: /tmp/OMI
        state: directory
        mode: '0755'
        
    - name: Check for /var/opt/OV directory and create if not exist.
      file:
        path: /var/opt/OV
        state: directory
        mode: '0755'
        
    - name: copy OM Installer package from url
      get_url:
        url: https://awxfs.tools.sgns.net/test/Agents/12.23_oa_media_Linux3.10_X64.zip
        dest: '/tmp/OMI'
        mode: '0755'
        url_username: "{{ Mirror_UN }}"
        url_password: "{{ Mirror_PW }}"
     
    - name: Unarchive to OMI directory
      unarchive:
        src: /tmp/OMI/12.23_oa_media_Linux3.10_X64.zip
        dest: /tmp/OMI
        copy: no
        mode: '0755'
        
    - name: Copy OMAgent install scripts on to target
      copy: 
        src: files/scripts/OMIScripts
        dest: '/tmp/OMI'
        remote_src: no
        mode: '0755'
    
    - name: set OMI directory permissions
      command: chmod -R 755 /tmp/OMI 
    
    - name: Run OMAgentLinuxInstall script on target host
      shell: sh /tmp/OMI/OMIScripts/OMAgentLinuxInstall.sh {{ mgmtIp }} {{ sntCode }}
      register: result1
      
    - name: print OMAgentLinuxInstall script output
      debug:
        msg: "Script output is: {{ result1 }}"
        
    - name: Run OMAgnetLinuxValidation script on target host
      shell: sh /tmp/OMI/OMIScripts/OMAgnetLinuxValidation.sh
      register: result2
      
    - name: print OMAgnetLinuxValidation script output
      debug:
        msg: "Script output is: {{ result2 }}"
        
    - name: Cleanup packages and scripts 
      file:
        path: /tmp/OMI
        state: absent
                   
