- name: OMI Tool Agent Installation
  hosts: all
  tasks:
    - name: Print Message
      debug:
        msg: "OMI Agent Installation!!"
    
    - name: Copy install OMI powershell scripts on to target
      win_copy: 
        src: files/scripts/OMIScripts
        dest: 'C:\sungard_files\'
        remote_src: no
    
    - name: Run installOMI script on target host
      win_shell: C:\\sungard_files\\OMIScripts\\installOMI.ps1
      register: result1
      
    - name: print installOMI script output
      debug:
        msg: "Script output is: {{ result1 }}"
        
    - name: run testOMI script on target host
      win_shell: C:\\sungard_files\\OMIScripts\\testOMI.ps1 -snt_code {{ sntCode }} -mgmt_ip {{ mgmtIp }}
      register: result2
      
    - name: print testOMI script output
      debug:
        msg: "Script output is: {{ result2 }}"
        
    - name: run ValidateOMIStatus script on target host
      win_shell: C:\\sungard_files\\OMIScripts\\ValidateOMIStatus.ps1
      register: result3
      
    - name: print ValidateOMIStatus script output
      debug:
        msg: "Script output is: {{ result3 }}"
