- name: OMI Tool Agent Installation
  hosts: all
  tasks:
    - name: Print Message
      debug:
        msg: "OMI Agent Installation!!"
    
    - name: Check for /tmp/OMI directory.
      stat:
        path: /tmp/OMI
      register: myDir
       
    - name: echo if the directory already exist
      debug:
        msg: "/tmp/OMI directory is already exist."
      when: myDir.stat.exists
     
    - name: Create /tmp/OMI directory if not exists 
      file:
        path: /tmp/OMI
        state: directory
        mode: '0755'
      when: myDir.stat.exists == false
      
    - name: Copy OM Installer package from url
      ansible.builtin.get_url:
        url: https://awxfs.tools.sgns.net/test/Agents/12.23_oa_media_Linux3.10_X64.zip
        dest: /tmp/OMI
        username: "{{ Mirror_UN }}"
        password: "{{ Mirror_PW }}"
    
    - name: Copy install OMI scripts on to target
      copy: 
        src: files/scripts/OMIScripts
        dest: /tmp/OMI
        remote_src: no
        mode: '0755'
    
    - name: set OMI directory permissions
      command: chmod -R 755 /tmp/OMI  
    
    - name: Unarchive to OMI folder
      unarchive: 
        src: /tmp/OMI/12.23_oa_media_Linux3.10_X64.zip
        dest: /tmp/OMI
        
    - name: Run OMAgentLinuxInstall script on target host
      command: sh /tmp/OMI/OMIScripts/OMAgentLinuxInstall.sh {{ mgmtIp }} {{ sntCode }}
      register: result1
       
    - name: print OMAgentLinuxInstall script output
      debug:
        msg: "Script output is: {{ result1 }}"
        
    - name: Run OMAgnetLinuxValidation script on target host
      command: sh /tmp/OMI/OMIScripts/OMAgnetLinuxValidation.sh
      register: result2
       
    - name: print OMAgnetLinuxValidation script output
      debug:
        msg: "Script output is: {{ result2 }}"
     
    - name: Cleanup packages and scripts
      ansible.builtin.file:
        path: /tmp/OMI
        state: absent
     
