- name: Tools Agent Installation
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "OMI Agent Installation!!"
    - name: run testOMI script on target host
      win_shell: C:\\sungard_files\\Scripts\\testOMI.ps1
        