- name: UD Tool Agent Installation
  hosts: all
  tasks:
    - name: Print Message
      debug:
        msg: "UD Agent Installation!!"
    
    - name: Check for /opt/HP/udagent directory and create if not exist.
      file:
       path: /opt/HP/udagent
       state: directory
       mode: '0755'
    
    - name: Copy UD Installer package from url
      get_url:
        url: "{{ item }}"
        dest: /opt/HP/udagent
        mode: '0755'
        username: "{{ Mirror_UN }}"
        password: "{{ Mirror_PW }}"
      loop: 
        - https://awxfs.tools.sgns.net/test/Agents/agentinstall_unix.zip
        - https://awxfs.tools.sgns.net/test/Agents/certs.zip
        - https://awxfs.tools.sgns.net/test/Agents/hp-ud-agent-linux.zip
     
    - name: Unarchive to udagent directory
      unarchive: 
        src: /opt/HP/udagent/"{{ item }}"
        dest: /opt/HP/udagent
        mode: '0755'
        remote_src: no
      with_items:
        - agentinstall_unix.zip
        - certs.zip
        - hp-ud-agent-linux.zip
        
    - name: Copy install UD scripts on to target
      copy: 
        src: files/scripts/UDScripts
        dest: /opt/HP/udagent
        remote_src: no
        mode: '0755'
    
    - name: set udagent directory permissions
      command: chmod -R 755 /opt/HP/udagent
      
    - name: Run UDAgentLinuxInstall script on target host
      shell: sh /opt/HP/udagent/UDScripts/UDAgentLinuxInstall.sh {{ probeIp }}
      register: result1
      
    - name: print udAgentInstall script output
      debug:
        msg: "Script output is: {{ result1 }}"
    
    - name: Cleanup packages and scripts 
      file:
        path: /opt/HP/udagent
        state: absent
