- name: UD Tool Agent Installation
  hosts: all
  tasks:
    - name: Print Message
      debug:
        msg: "UD Agent Installation!!"
        
    - name: Run udAgentInstall script on target host
      win_shell: C:\\sungard_files\\Scripts\\udAgentInstall.ps1 -probe_ip {{ probeIp }}
      register: result1
      
    - name: print installOMI script output
      debug:
        msg: "Script output is: {{ result1 }}"
