- name: create dynamic inventory
  hosts: localhost
  tasks:
    - name: set fqdn variable
      set_fact: 
        fqdn: " {{ hostName }}.{{sntCode}}.omi.local"  
    - name: print fqdn
      debug:
        msg: "{{ fqdn }}"
    - name: adding host to Windows inventory
      add_host:
        name: "{{ fqdn }}"
        inventory_id: "2"
