- name: check host value
  hosts: localhost
  tasks:
    - name: set variable
      set_fact: 
        hName: " {{ hostName }} | split('.') | first"  
    - name: check hostname
      debug:
        msg: "{{ hName }}"
