- name: Get username signed in to AWX
  hosts: localhost
  tasks:
    - name: print user
      debug:
        msg: "{{ awx_user_name }}"

    - name: set host fqdn variable
      set_fact: 
        fqdn: "{{ hostName }}.{{sntCode}}.{{ domainName }}" 

    - name: print fqdn
      debug:
        msg: "{{ fqdn }}"
