- name: Tools Agent Installation
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello User"
    - name: Unarchive to OMI folder
      ansible.windows.win_powershell:
        script: |
          Expand-Archive -Path "C:\sungard_files\OMI\HPEOpsBAgent_Windows_12.20.05_BASE.zip" -DestinationPath "C:\sungard_files\OMI" -Force   
