- name: get username logged
  hosts: localhost
  tasks:
    - name: print user
      debug:
        msg: "{{ awx_user_name }}"

    - name: set host fqdn variable
      set_fact: 
        fqdn: "{{ hostName }}.{{sntCode}}.omi.local" 

    - name: print fqdn
      debug:
        msg: "{{ fqdn }}"

    - name: create user on target host
      win_user: 
        name: "sas-{{ awx_user_name }}"
        state: absent
      delegate_to: "{{ fqdn }}"          
      register: userOut

    - name: print userOut result
      debug: 
        msg: "{{ userOut }}"
