- name: create dynamic inventory
  hosts: localhost
  tasks:
    - name: set fqdn variable
      set_fact: 
        fqdn: " {{ hostName }}.{{sntCode}}.omi.local"  
    - name: print fqdn
      debug:
        msg: "{{ fqdn }}"

    - name: create inventory
      uri: 
        url: http://bt-c9-stream-tmp.oamp.sgns.net/api/v2/inventories/
        user: "{{ Mirror_UN }}"
        password: "{{ Mirror_PW }}"
        method: POST  
        body: |-
              {
                  "name": "{{ sntCode }}_Windows2022",
                  "description": "{{ sntCode }} Windows 2022 Inventory",
                  "organization": "1",
                  "variables": "{ 'ansible_port': 31457, 'ansible_winrm_transport': 'credssp', 'ansible_connection': 'winrm', 'ansible_winrm_scheme': 'https' }"
              }
        body_format: json
        force_basic_auth: yes
        status_code: 201, 200, 400    
        validate_certs: no
      register: inventResponse   

    - name: print create inventory response
      debug:
        msg: "{{ inventResponse }}"
      tags: 
        - always   

    # - debug: 
    #     msg: "{{ sntCode }}_Windows2022 Inventory is created successfully."
    #   when: (inventResponse.status == 201) or (inventResponse.status == 200)

    - debug: 
        msg: "{{ sntCode }}_Windows2022 Inventory is already exist."
      when: inventResponse.status == 400      

    - name: check inventory 
      uri: 
        url: http://bt-c9-stream-tmp.oamp.sgns.net/api/v2/inventories/?name={{ sntCode }}_Windows2022
        user: "{{ Mirror_UN }}"
        password: "{{ Mirror_PW }}"
        method: GET  
        body_format: json
        force_basic_auth: yes
        status_code: 201, 200, 400    
        validate_certs: no
      register: inventoryResponse1

    - name: print get inventory response
      debug:
        msg: "{{ inventoryResponse1 }}" 

    - debug: 
        msg: "{{ sntCode }}_Windows2022 inventory exists and verified."
      when: inventoryResponse1.json.results.name == sntCode_Windows2022

    - name: adding host to Windows inventory
      uri:
       url: http://bt-c9-stream-tmp.oamp.sgns.net/api/v2/inventories/{{ inventoryResponse1.json.results[0].id }}/hosts/
       user: "{{ Mirror_UN }}"
       password: "{{ Mirror_PW }}"
       method: POST
       body: '{ "name" : "{{ fqdn }}" }'
       force_basic_auth: yes
       status_code: 201, 200, 400
       body_format: json
       validate_certs: no
      when: inventoryResponse1.json.results[0].id != 0

    - name: pring add host to inventory response
      debug:
        msg: "{{ addHostInvent }}"

      
    - name: update inventory details
      uri: 
        url: http://bt-c9-stream-tmp.oamp.sgns.net/api/v2/job_templates/27/
        user: "{{ Mirror_UN }}"
        password: "{{ Mirror_PW }}"
        method: patch  
        body: |-
              {
                "inventory": "{{ inventoryResponse1.json.results[0].id }}"

              }
        body_format: json
        force_basic_auth: yes
        status_code: 201, 200, 400    
        validate_certs: no
      register: inventoryResponse2

    - name: print response
      debug:
        msg: "{{ inventoryResponse2 }}"

    - debug:
        msg: "test1 Job Template is updated with the inventory name {{ sntCode }}_Windows2022." 
      when: inventoryResponse2.json.summary_fields.inventory.name == {{ sntCode }}_Windows2022
