- name: check host value
  hosts: localhost
  tasks:
    - name: read hostname
      set_fact:
        hName = "{{ hostName }}" | split(.) | first
    - name: check hostname
      debug: 
        msg: "{{ hName }}"
