- name: create dynamic inventory
  hosts: localhost
  tasks:
    - name: set fqdn variable
      set_fact: 
        fqdn: " {{ hostName }}.{{sntCode}}.omi.local"  
    - name: print fqdn
      debug:
        msg: "{{ fqdn }}"
    - name: adding host to Windows inventory
      uri:
       url: http://bt-c9-stream-tmp.oamp.sgns.net/api/v2/inventories/2/hosts/
       user: "{{ Mirror_UN }}"
       password: "{{ Mirror_PW }}"
       method: POST
       body: '{ "name" : "{{ fqdn }}" }'
       force_basic_auth: yes
       status_code: 201, 200, 400
       body_format: json
       validate_certs: no
      
