- name: delete record from Bind DNS
  uri:
    url: https://{{ ESBURL }}:{{ ESBPORT }}/dns/zone/sahd/records
    method: delete
    body_format: json
    headers: 
        content-type: application/json
        Authorization: "{{ ESBAuth }}"
    status_code: 200, 201
    body: |-
          [ 
            ["{{ hostName }}","mgmtIp"]
          ]
  register: addRecord      
    
- name: Print add record response
  debug:
    msg: "{{ addRecord }}"
