- name: Print Message
  debug:
    msg: "Running Install and Configure SNMP!!"

- name: check hostname
  win_command: hostname
  register: cmdOut
  
- name: ping output
  debug:
    msg: "{{ cmdOut }}"
