- name: "Check IpAddress is registered with zone in DNS"
  uri:
    url: https://"{{ ESBURL }}":"{{ ESBPORT }}"/dns/lookup?query={{ mgmtIp }}
    method: GET
    body_format: json
    headers: 
        content-type: application/json
        Authorization: "{{ ESBAuth }}"
    status_code: 200, 404
  register: hostFQDN

- name: print hostFQDN
  debug: 
    msg: "{{ hostFQDN }}"

- name: Check host fqdn is registered with zone in DNS
  uri:
    url: https://"{{ ESBURL }}":"{{ ESBPORT }}"/dns/lookup?query={{ hostName }}.{{ sntCode }}.omi.local
    method: GET
    body_format: json
    headers: 
        content-type: application/json
        Authorization: "{{ ESBAuth }}"
    status_code: 200, 404
  register: ipAddrs
    
- name: print ipAddrs
  debug: 
    msg: "{{ ipAddrs }}"

- name: add record
  uri:
    url: https://"{{ ESBURL }}"":"{{ ESBPORT }}"/dns/zone/sahd/records?create_zones=true
    method: Post
    body_format: raw
    headers: 
        content-type: application/json
        Authorization: "{{ ESBAuth }}"
    status_code: 200, 201
    body: |-   
          [ 
            ["{{ hostName }}","{{ mgmtIp }}"]
          ]  
  when: ((hostDetails.json.status is defined ) and (hostFQDN.json.status == "not found")) or ((ipAddrs.json.status is defined) and (ipAddrs.json[0].status == "not found"))
