- name: "Check IpAddress is registered with zone in DNS"
  uri:
    url: https://esb-stage.tools.sgns.net:443/dns/lookup?query=10.66.241.175
    method: GET
    body_format: json
    headers: 
        content-type: application/json
        Authorization: "{{ Esb_Stg }}"
    status_code: 200, 404
  delegate_to: localhost
  register: hostFQDN

- name: Check host fqdn is registered with zone in DNS
  uri:
    url: https://esb-stage.tools.sgns.net:443/dns/lookup?query=RAtest-win2k22M.sahd.omi.local
    method: GET
    body_format: json
    headers: 
        content-type: application/json
        Authorization: "{{ Esb_Stg }}"
    status_code: 200, 404
  delegate_to: localhost
  register: ipAddrs
    
- name: add record
  uri:
    url: https://esb-stage.tools.sgns.net:443/dns/zone/sahd/records?create_zones=true
    method: Post
    body_format: raw
    headers: 
        content-type: application/json
        Authorization: "{{ Esb_Stg }}"
    status_code: 200, 201
    body: |-   
          [ 
            ["RAtest-win2k22M","10.66.241.175"]
          ]  
  delegate_to: localhost
  when: (hostFQDN.json.status == "not found") or (ipAddrs.json.status == "not found")
