- name: "Check IpAddress is registered with zone in DNS"
  uri:
    url: https://esb-stage.tools.sgns.net:443/dns/lookup?query=mgmtIp
    method: GET
    body_format: json
    headers: 
        content-type: application/json
        Authorization: "{{ Esb_Stg }}"
    status_code: 200, 404
  register: hostFQDN

- name: print hostFQDN
  debug: 
    msg: "{{ hostFQDN }}"

- name: Check host fqdn is registered with zone in DNS
  uri:
    url: https://esb-stage.tools.sgns.net:443/dns/lookup?query= hostName.sntCode.omi.local
    method: GET
    body_format: json
    headers: 
        content-type: application/json
        Authorization: "{{ Esb_Stg }}"
    status_code: 200, 404
  register: ipAddrs
    
- name: print ipAddrs
  debug: 
    msg: "{{ ipAddrs }}"

- name: add record
  uri:
    url: https://esb-stage.tools.sgns.net:443/dns/zone/sahd/records?create_zones=true
    method: Post
    body_format: raw
    headers: 
        content-type: application/json
        Authorization: "{{ Esb_Stg }}"
    status_code: 200, 201
    body: |-   
          [ 
            ["hostName","mgmtIp"]
          ]  
  when: ((hostDetails.json.status is defined ) and (hostFQDN.json.status == "not found")) or ((ipAddrs.json.status is defined) and (ipAddrs.json[0].status == "not found"))
