- name: set host fqdn variable
  set_fact: 
    fqdn: " {{ hostName }}.{{sntCode}}.omi.local"  
    
- name: print host fqdn name
  debug:
    msg: "{{ fqdn }}"
    
- name: add host fqdn name to Windows Inventory
  uri:
    url: http://{{ awxHost }}/api/v2/inventories/{{ inventoryID }}/hosts/
    user: "{{ Mirror_UN }}"
    password: "{{ Mirror_PW }}"
    method: POST
    body: '{ "name" : "{{ fqdn }}" }'
    force_basic_auth: yes
    status_code: 201, 200, 400
    body_format: json
    validate_certs: no
