- name: Get Auth Token from SEPM
  uri:
    url: https://{{ ESBURL }}:{{ ESBPORT }}/services/sepm/authToken?customerRegion=US
    method: Post
    body_format: json
    headers: 
        content-type: application/json
        Authorization: "{{ ESBAuth }}"
    status_code: 200, 201
    body: |-
          {
            "username" : "{{ SEPM_UN }}",
            "password" : "{{ SEPM_PW }}",
            "domain" : ""
          }
  register: AuthKey
  failed_when: "'token' in AuthKey.json"

- fail:
    msg: "FAILED::Failed to create Auth token."  
  when: AuthKey.json | length == 0

- debug: 
    msg: "{{ AuthKey }}"

- name: Get group details for the snt code given
  uri:
    url: https://{{ ESBURL }}:{{ ESBPORT }}/services/sepm/group?customerRegion=US&authToken={{ AuthKey.json.token }}&groupName={{ sntCode | upper }}&operator=contains
    method: Get
    body_format: json
    headers:
        content-type: application/json
        Authorization: "{{ ESBAuth }}"
    status_code: 200, 201
    
  when: AuthKey.json.token | length != 0
  register: groupId  

- fail:
    msg: "FAILED::Failed to get group details."  
  when: groupId.json | length == 0

- debug: 
    msg: "{{ groupId }}"  
      
- name: Get computer details for the snt code given
  uri:
    url: https://{{ ESBURL }}:{{ ESBPORT }}/services/sepm/computers?customerRegion=US&authToken={{ AuthKey.json.token }}&computerName={{ hostName }}
    method: Get
    body_format: json
    headers:
        content-type: application/json
        Authorization: "{{ ESBAuth }}"
    status_code: 200, 201
  register: compDetails

- fail:
    msg: "FAILED::Failed to get computer details."  
  when: compDetails.json.content | length == 0

- debug: 
    msg: "{{ compDetails }}"  

